theme: minima
title: My Coding Journey
author: Paul Danso Asare
description: Economics and Tech Enthusiast | HTML5, CSS, Python, JavaScript, and React | Problem Solver | Lifelong Learner | Data Analysis
